program: grid_search.py
method: grid
name: IVF_FLAT_search
metric:
  goal: minimize
  name: loss
index_type:
  values: ["HNSW"]
parameters:
  build_M:
      values: range(4,64,10)
  build_efConstruction:
      values: range(8,512,50)
  search_ef:
      values: range(100,32768,100)