program: grid_search.py
method: grid
name: IVF_FLAT
metric:
  goal: minimize
  name: loss
parameters:
  index_type:
    values: ["IVF_FLAT"]
  build_nlist:
    values: []
  search_nprobe:
    values: []
    
    
  