program: grid_search.py
method: grid
name: IVF_FLAT_search
metric:
  goal: minimize
  name: loss
index_type:
  values: ["IVF_FLAT"]
parameters:
  index_params:
    nlist:
      values: range(1,1024,10)
    ef:
      values: [1,2]
  search_params:
    nprobe:
      values: range(1,nlist,10)
